// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;

public class Tools
{
	public Tools () {
	}

	public static int convertToMS(double seconds) {
		return (int) (seconds*1000.0d);
	}

	public static double convertToSeconds(int ms) {
		return ((double) ms/1000.0d);
	}

	public static int getSamplesPerTicks(AudioClip music, int bpm) {
		double secondsPerTicks = (60.0d / ((double) bpm));
		return (int) (music.frequency * (60.0d / ((double) bpm)));
	}

}

